Uygulama/Models/KonuIcerikleris.cs
using EgitimPortali.DTO;

namespace Uygulama.Models
{
    public class KonuIcerikleris
    {
        public IEnumerable<DersIcerikleriDto> dersIcerikleriDtos  { get; set; }
        public IEnumerable<TestDto> Tests { get; set; }
    }
}

Uygulama/Controllers/KonularController.cs
using EgitimPortali.DTO;
using EgitimPortali.Request.Konular;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;

namespace Uygulama.Controllers
{
    [Authorize(Roles = "Admin")]

    public class KonularController : Controller
    {
        public async Task<IActionResult> ButunKonular()
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/Konular");
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<List<KonularDto>>(jsonString);
            if (values != null)
                return View(values);
            else
                return RedirectToAction("GirisYap", "Login");
        }
        [HttpGet]
        public async Task<IActionResult> YeniKonuEkle()
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage2 = await httpClient.GetAsync("https://localhost:7179/api/Dersler");
            var jsonString = await responseMessage2.Content.ReadAsStringAsync();
            var values2 = JsonConvert.DeserializeObject<List<DerslerDto>>(jsonString);
            List<SelectListItem> categoryvalue = (from x in values2
                                                  select new SelectListItem
                                                  {
                                                      Text = x.Name,
                                                      Value = x.Id.ToString()

                                                  }).ToList();
            ViewBag.cv = categoryvalue;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> YeniKonuEkle(KonularPostRequest p)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage2 = await httpClient.GetAsync("https://localhost:7179/api/Dersler");
            var jsonString = await responseMessage2.Content.ReadAsStringAsync();
            var values2 = JsonConvert.DeserializeObject<List<DerslerDto>>(jsonString);
            List<SelectListItem> categoryvalue = (from x in values2
                                                  select new SelectListItem
                                                  {
                                                      Text = x.Name,
                                                      Value = x.Id.ToString()

                                                  }).ToList();
            ViewBag.cv = categoryvalue;

            var jsonEmployee = JsonConvert.SerializeObject(p);
            StringContent content = new StringContent(jsonEmployee, Encoding.UTF8, "application/json");
            var responseMessage = await httpClient.PostAsync("https://localhost:7179/api/Konular", content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("ButunKonular");
            }
            return View(p);
        }
        [HttpGet]
        public async Task<IActionResult> KonuGuncelle(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage2 = await httpClient.GetAsync("https://localhost:7179/api/Dersler");
            var jsonString = await responseMessage2.Content.ReadAsStringAsync();
            var values2 = JsonConvert.DeserializeObject<List<DerslerDto>>(jsonString);
            List<SelectListItem> categoryvalue = (from x in values2
                                                  select new SelectListItem
                                                  {
                                                      Text = x.Name,
                                                      Value = x.Id.ToString()

                                                  }).ToList();
            ViewBag.cv = categoryvalue;
            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/Konular/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonEmployee = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<KonularUpdateRequest>(jsonEmployee);
                if (values != null)
                    return View(values);
                else
                    return RedirectToAction("GirisYap", "Login");
            }
            return RedirectToAction("ButunKonular");
        }
        [HttpPost]
        public async Task<IActionResult> KonuGuncelle(KonularUpdateRequest p)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var jsonEmployee = JsonConvert.SerializeObject(p);
            var content = new StringContent(jsonEmployee, Encoding.UTF8, "application/json");
            var responseMessage = await httpClient.PutAsync("https://localhost:7179/api/Konular/" + p.Id, content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("ButunKonular");
            }
            return View(p);
        }
        public async Task<IActionResult> KonuSil(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.DeleteAsync("https://localhost:7179/api/Konular/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("ButunKonular");
            }
            return View();
        }
    }
}

Uygulama/Controllers/OgretmenController.cs
using EgitimPortali.DTO;
using EgitimPortali.Models;
using EgitimPortali.Request.DersIcerikleri;
using EgitimPortali.Request.Konular;
using EgitimPortali.Request.Test;
using EgitimPortali.Request.TestSoru;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Data;
using System.Net.Http.Headers;
using System.Text;
using Uygulama.Models;

namespace Uygulama.Controllers
{
    [Authorize(Roles = "Öğretmen,Admin")]
    public class OgretmenController : Controller
    {
        public async Task<IActionResult> Konular(int id)
        {       
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");
            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/Konular/konular/" + id);
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<List<KonularDto>>(jsonString);
            ViewBag.cv = id;
            if (values != null)
                return View(values);
            else
                return RedirectToAction("GirisYap", "Login");
        }
        public async Task<IActionResult> KonuIcerikleri(int id)
        {        
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            ViewBag.id = id;
            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/DersIcerikleri/konular/" + id);
        
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<IEnumerable<DersIcerikleriDto>>(jsonString);
        


            var responseMessage2 = await httpClient.GetAsync("https://localhost:7179/api/Test/konu/" + id);
            var jsonString2 = await responseMessage2.Content.ReadAsStringAsync();
            var values2 = JsonConvert.DeserializeObject<IEnumerable<TestDto>>(jsonString2);           
            KonuIcerikleris cs = new KonuIcerikleris();     
            cs.dersIcerikleriDtos = values;
            cs.Tests = values2;
            if (cs != null)
                return View(cs);
            else
                return RedirectToAction("GirisYap", "Login");
        }
        [HttpGet]
        public async Task<IActionResult> KonuEkle(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage2 = await httpClient.GetAsync("https://localhost:7179/api/Dersler");
            var jsonString = await responseMessage2.Content.ReadAsStringAsync();
            var values2 = JsonConvert.DeserializeObject<List<DerslerDto>>(jsonString);            
            ViewBag.cv = id;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> KonuEkle(KonularPostRequest p)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            ViewBag.cv = p.DerslerID;
            var jsonEmployee = JsonConvert.SerializeObject(p);
            StringContent content = new StringContent(jsonEmployee, Encoding.UTF8, "application/json");
            var responseMessage = await httpClient.PostAsync("https://localhost:7179/api/Konular", content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Konular", new { id = p.DerslerID });
            }
            return View(p);
        }


        public async Task<IActionResult> DersinSorulari(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/Sorular/dersleregore/" + id);
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<List<SorularDto>>(jsonString);
            return View(values);
        }
        public async Task<IActionResult> DerseGelenYanitlar(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/SorularinCevaplari/cevaplar/" + id);
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<List<SoruCevapDto>>(jsonString);
            return View(values);
        }
        public async Task<IActionResult> YorumuOnayla(int id)
        {

            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");
            var jsonEmployee = JsonConvert.SerializeObject(id);
            var content = new StringContent(jsonEmployee, Encoding.UTF8, "application/json");
            var responseMessage = await httpClient.PutAsync("https://localhost:7179/api/SorularinCevaplari/" + id, content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("IzlenilenDersler");
            }
            return Json(id);
        }
        public async Task<IActionResult> YanitKaldir(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.DeleteAsync("https://localhost:7179/api/SorularinCevaplari/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("KonuIcerikleri");
            }
            return View();
        }
        public async Task<IActionResult> YorumKaldir(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.DeleteAsync("https://localhost:7179/api/Yorumlar/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("KonuIcerikleri");
            }
            return View();
        }

        public async Task<IActionResult> DerseGelenYorumlar(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/Yorumlar/yorumlar/" + id);
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<List<YorumlarDto>>(jsonString);
            return View(values);
        }
        public async Task<IActionResult> IcerikSil(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.DeleteAsync("https://localhost:7179/api/DersIcerikleri/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("KonuIcerikleri");
            }
            return View();
        }
        public async Task<IActionResult> KonuSil(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.DeleteAsync("https://localhost:7179/api/Konular/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Konular", new { id = id });
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> KonuGuncelle(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

    
            ViewBag.cv = id;
            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/Konular/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonEmployee = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<KonularUpdateRequest>(jsonEmployee);
                if (values != null)
                    return View(values);
                else
                    return RedirectToAction("GirisYap", "Login");
            }
            return RedirectToAction("Konular");
        }
        [HttpPost]
        public async Task<IActionResult> KonuGuncelle(KonularUpdateRequest p)
        {

Uygulama/Views/Ogretmen/DerseGelenYanitlar.cshtml
@using EgitimPortali.DTO
@model List<SoruCevapDto>
@{
    ViewData["Title"] = "DerseGelenYanitlar";
    Layout = "~/Views/Shared/_OgretmenLayout.cshtml";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-md-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Yanıtlar</h5>
                </div>
                <div class="ibox-content">
                    <div class="row m-b-sm m-t-sm">

                     
                    </div>
                    <br />
                    <div class="table-responsive">
                        @foreach (var x in Model)
                        {
                            <table class="table shoping-cart-table">
                                <tbody>
                                    <tr>
                                        <td class="desc">
                                            <p class="small">
                                                @Html.Raw(x.Icerik)
                                            </p>
                                            <div class="m-t-sm">
                                                @if(x.Dogruluk == false)
                                                {
                                                    <a href="/Ogretmen/YorumuOnayla/@x.Id" data-id="@x.Id" class="text-muted demo5"><i class="fa fa-check"></i> Yorumu Onayla</a>
                                                }
                                                else

                                                {
                                                    <a href="/Ogretmen/YorumuOnayla/@x.Id" data-id="@x.Id" class="text-muted demo6"><i class="fa fa-check"></i> Yorumun Onayını kaldır</a>
                                                }
                                                &nbsp;
                                                <a href="/Ogretmen/YanitKaldir/@x.Id" data-id="@x.Id" class="text-muted demo4"><i class="fa fa-trash"></i> Yorumu Kaldır</a>
                                            </div>
                                        </td>
                                        <td width="200">
                                            <h4>
                                                @(((DateTime)x.CreatedAt).ToString("dd-MMM-yyyy"))
                                            </h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <hr />
                        }
                    </div>
                </div>
                <div class="ibox-content">
                    @*                    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
                    *@
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/admin/js/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    $('.demo4').on('click', function (event) {
        event.preventDefault();
        var btn = $(this);
        const url = $(this).attr('href');
        swal({
            title: 'Yorumu Kaldırmak İstediğinizden Emin Misiniz ?',
            text: "Yorumunuzu kaldırmanız durumunda dersin altında gözükmeyecektir.",
            icon: 'info',
            buttons: ["Vazgeç", "Onayla!"],
        }).then(function (value) {
            if (value) {
                var id = btn.data("id");
                $.ajax({
                    url: "/Ogretmen/DersinSorusunaGelenYanitSil/" + id,
                    type: "post",
                    dataType: "json",
                    success: function (func) {
                        window.location.reload();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        window.location.reload();
                    }
                });
            }
        });
    });
    $('.demo5').on('click', function (event) {
        event.preventDefault();
        var btn = $(this);
        const url = $(this).attr('href');
        swal({
            title: 'Yorumu Onaylamak İstediğinizden Emin Misiniz ?',
            text: "Yorumunuzu onaylamanız durumunda dersin sorunun onaylı olarak gözükecektir.",
            icon: 'info',
            buttons: ["Vazgeç", "Onayla!"],
        }).then(function (value) {
            if (value) {
                var id = btn.data("id");
                $.ajax({
                    url: "/Ogretmen/YorumuOnayla/" + id,
                    type: "post",
                    dataType: "json",
                    success: function (func) {
                        window.location.reload();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        window.location.reload();
                    }
                });
            }
        });
    });
    $('.demo6').on('click', function (event) {
        event.preventDefault();
        var btn = $(this);
        const url = $(this).attr('href');
        swal({
            title: 'Yorumun Onayını Kaldırmak İstediğinizden Emin Misiniz ?',
            text: "Yorumunuzu onayını kaldırmanız durumunda sorunun altında onaylı olarak gözükmeyecektir.",
            icon: 'info',
            buttons: ["Vazgeç", "Onayla!"],
        }).then(function (value) {
            if (value) {
                var id = btn.data("id");
                $.ajax({
                    url: "/Ogretmen/YorumuOnayla/" + id,
                    type: "post",
                    dataType: "json",
                    success: function (func) {
                        window.location.reload();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        window.location.reload();
                    }
                });
            }
        });
    });
</script>

Uygulama/Views/Ogretmen/DerseGelenYorumlar.cshtml
@using EgitimPortali.DTO
@model List<YorumlarDto>
@{
    ViewData["Title"] = "DerseGelenYorumlar";
    Layout = "~/Views/Shared/_OgretmenLayout.cshtml";
}


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-md-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Yanıtlar</h5>
                </div>
                <div class="ibox-content">
                   
                    <br />
                    <div class="table-responsive">
                        @foreach (var x in Model)
                        {
                            <table class="table shoping-cart-table">
                                <tbody>
                                    <tr>
                                        <td width="90">
                                            <img src="@x.DersIcerikleri.Resim" style="max-width:100%;" />
                                        </td>
                                        <td class="desc">
                                            <p class="small">
                                                @x.Name
                                            </p>
                                            <div class="m-t-sm">

                                                <a href="/Ogretmen/YorumKaldir/@x.Id" class="text-muted"><i class="fa fa-trash"></i> Yorumu Kaldır</a>
                                            </div>
                                        </td>
                                        <td width="200">
                                            <h4>
                                                @(((DateTime)x.CreatedAt).ToString("dd-MMM-yyyy"))
                                            </h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <hr />
                        }
                    </div>
                </div>
                <div class="ibox-content">
                    @*                    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
                    *@
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/admin/js/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    $('.demo4').on('click', function (event) {
        event.preventDefault();
        var btn = $(this);
        const url = $(this).attr('href');
        swal({
            title: 'Yorumu Kaldırmak İstediğinizden Emin Misiniz ?',
            text: "Yorumunuzu kaldırmanız durumunda dersin altında gözükmeyecektir.",
            icon: 'info',
            buttons: ["Vazgeç", "Onayla!"],
        }).then(function (value) {
            if (value) {
                var id = btn.data("id");
                $.ajax({
                    url: "/Ogretmen/YorumKaldir/" + id,
                    type: "post",
                    dataType: "json",
                    success: function (func) {
                        window.location.reload();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        window.location.reload();
                    }
                });
            }
        });
    });
   
    
</script>

Uygulama/Views/Ogretmen/KonuEkle.cshtml
@using EgitimPortali.Request.Konular
@model KonularPostRequest
@{
    ViewData["Title"] = "KonuEkle";
    Layout = "~/Views/Shared/_OgretmenLayout.cshtml";
}

<h1>Yeni Konu Ekleme Sayfası</h1>
@using (Html.BeginForm("KonuEkle", "Ogretmen", FormMethod.Post))
{   
@*    <select asp-for="DerslerID" class="form-control" asp-items="@(List<SelectListItem>)ViewBag.cv">
         <option>Lütfen Konu Seçiniz</option>
    </select>*@
    <input type="hidden" asp-for="DerslerID" value="@ViewBag.cv" />

    <br />
    @Html.Label("Konu Adı")
    @Html.TextBoxFor(x=>x.Name, new { @class = "form-control" })
    @Html.Label("Konu Görseli")
    @Html.TextBoxFor(x=>x.Resim, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Ekle</button>
}

Uygulama/Views/Ogretmen/KonuGuncelle.cshtml
@using EgitimPortali.Request.Konular
@model KonularUpdateRequest
@{
    ViewData["Title"] = "KonuGuncelle";
    Layout = "~/Views/Shared/_OgretmenLayout.cshtml";
}

<h1>Konu Güncelleme Sayfası</h1>

@using (Html.BeginForm("KonuGuncelle", "Ogretmen", FormMethod.Post))
{

    <input type="hidden" asp-for="DerslerID"/>
   @* <select asp-for="DerslerID" class="form-control" asp-items="@(List<SelectListItem>)ViewBag.cv">
        <option>Lütfen Konu Seçiniz</option>
    </select>*@

    <br />
    @Html.HiddenFor(x=>x.Id)

    @Html.Label("Konu Adı")
    @Html.TextBoxFor(x=>x.Name, new { @class = "form-control" })
    <br />
    @Html.Label("Konu Sırası")
    @Html.TextBoxFor(x=>x.KonuSirasi, new { @class = "form-control" })
    <br />
    @Html.Label("Konu Görseli")
    @Html.TextBoxFor(x=>x.Resim, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Güncelle</button>
}

Uygulama/Views/Ogretmen/TestEkle.cshtml
@using EgitimPortali.Request.Test
@model TestPostRequest
@{
    ViewData["Title"] = "TestEkle";
    Layout = "~/Views/Shared/_OgretmenLayout.cshtml";
}
<br />
<div class="col-lg-12">
    <div class="ibox ">
        <div class="ibox-title">
            <h5>Yeni Test Oluşturma Sayfası</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <form method="post">
                <input type="hidden" asp-for="KonularID" value="@ViewBag.id" />

                <div class="form-group row">
                    <label class="col-lg-2 col-form-label">Test Adı</label>
                    <div class="col-lg-10">
                        <input type="text" placeholder="Test Adı" name="Name" class="form-control">
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button type="submit" class="btn btn-primary">Test Oluştur</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

Uygulama/Views/Ogretmen/YeniDersIcerigiEkle.cshtml
@using EgitimPortali.Request.DersIcerikleri
@model DersIcerikleriPostRequest
@{
    ViewData["Title"] = "YeniDersIcerigiEkle";
    Layout = "~/Views/Shared/_OgretmenLayout.cshtml";
}

<head>
    <meta charset="UTF-8">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
</head>
<h1>Yeni Ders İçeriği Ekle</h1>

@using (Html.BeginForm("YeniDersIcerigiEkle", "Ogretmen", FormMethod.Post))
{
    <input type="hidden" asp-for="KonularID" value="@ViewBag.id" />
    <br />
    @Html.Label("İçerik Adı")
    @Html.TextBoxFor(x=>x.Name, new { @class = "form-control" })
    <br />

    @Html.Label("Ders İçeriği")
    <textarea id="summernote" asp-for="@Model.Icerik" class="form-control" required=""></textarea>
    <br />
    @Html.Label("Ders Görseli")
    @Html.TextBoxFor(x=>x.Resim, new { @class = "form-control" })
    <br />
    @Html.Label("Ders Pdfi")
    @Html.TextBoxFor(x=>x.PdfYolu, new { @class = "form-control" })
    <br />

    <script>
        $('#summernote').summernote({
            placeholder: 'İçerik',
            tabsize: 2,
            height: 200,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'video']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]
        });
    </script>

    <button class="btn btn-info">Oluştur</button>
}