Uygulama/Controllers/SorularController.cs
using EgitimPortali.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace Uygulama.Controllers
{
    [Authorize(Roles = "Admin")]

    public class SorularController : Controller
    {
        public async Task<IActionResult> ButunSorular()
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/Sorular/");
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<List<SorularDto>>(jsonString);
            if (values != null)
                return View(values);
            else
                return RedirectToAction("GirisYap", "Login");
        }
        public async Task<IActionResult> SorulayaGelenYanitlar(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/SorularinCevaplari/cevaplar/" + id);
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<List<SoruCevapDto>>(jsonString);
            if (values != null)
                return View(values);
            else
                return RedirectToAction("GirisYap", "Login");
        }
        public async Task<IActionResult> YanitSil(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.DeleteAsync("https://localhost:7179/api/Sorular/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("ButunSorular");
            }
            return View();
        }
    }
}

Uygulama/Controllers/YorumlarController.cs
using EgitimPortali.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace Uygulama.Controllers
{
    [Authorize(Roles = "Admin")]

    public class YorumlarController : Controller
    {
        public async Task<IActionResult> ButunYorumlar()
        {       
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/Yorumlar/");
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<List<YorumlarDto>>(jsonString);
            if (values != null)
                return View(values);
            else
                return RedirectToAction("GirisYap", "Login");
        }
        public async Task<IActionResult> YorumSil(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.DeleteAsync("https://localhost:7179/api/Yorumlar/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("ButunYorumlar");
            }
            return View();
        }
    
        public IActionResult DerslereIceriklerineGoreYorumlar()
        {
            return View();
        }
    }
}

Uygulama/Views/Sorular/ButunSorular.cshtml
@using EgitimPortali.DTO
@model List<SorularDto>
@{
    ViewData["Title"] = "ButunSorular";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="ibox ">
    <div class="ibox-title">
        <h5>Bütün Sorular</h5>
        <div class="ibox-tools">
        </div>
    </div>
    <div class="ibox-content">
        <table class="table">
            <thead>
                <tr>
                    <th><center></center></th>
                    <th><center>Ders</center></th>
                    <th><center>Soru Başlığı</center></th>
                    <th><center>Soruya Git</center></th>
                    <th><center>Soruya Gelen Yanıtlar</center></th>
                    <th><center>Soruyu Sil</center></th>
                </tr>
            </thead>
            @foreach (var x in Model)
            {
                <tr>
                    <td width="90">
                        <center>
                            <img src="~/edu-school-starter/assets/images/sorucevap.jpg" style="max-width:100%;" />
                        </center>

                    </td>
                    <td><center>@x.Dersler.Name</center></td>
                    <td><center>@x.Name</center></td>
                    <td><center><a href="/MerkezeTeget/SoruDetay/@x.Id" class="btn btn-warning"><i class="fa fa-link"></i> Soruya Git</a></center></td>
                    <td><center><a href="/Sorular/SorulayaGelenYanitlar/@x.Id" class="btn btn-success"><i class="fa fa-comments"></i> Soruya gelen yanıtlar</a></center></td>
                    <td><center><a href="/Sorular/YanitSil/@x.Id" data-id="@x.Id" class="btn btn-danger demo4"><i class="fa fa-trash"></i> Sil</a></center></td>
                </tr>
            }

        </table>
    </div>
</div>
<script src="~/admin/js/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    $('.demo4').on('click', function (event) {
        event.preventDefault();
        var btn = $(this);
        const url = $(this).attr('href');
        swal({
            title: 'Soruyu Silmek İstediğinizden Emin Misiniz ?',
            text: "Soruyu silmeniz durumunda kullanıcılar bu soruya bir daha asla ulaşamayacaktır.",
            icon: 'info',
            buttons: ["Vazgeç", "Onayla!"],
        }).then(function (value) {
            if (value) {
                var id = btn.data("id");
                $.ajax({
                    url: "/Sorular/YanitSil/" + id,
                    type: "post",
                    dataType: "json",
                    success: function (func) {
                        window.location.reload();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        window.location.reload();
                    }
                });
            }
        });
    });
</script>

Uygulama/Views/Sorular/SorulayaGelenYanitlar.cshtml
@using EgitimPortali.DTO
@model List<SoruCevapDto>
@{
    ViewData["Title"] = "SorulayaGelenYanitlar";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-md-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Yanıtlar</h5>
                </div>
                <div class="ibox-content">
                    <div class="row m-b-sm m-t-sm">

                        <div class="col-md-12">
                            @using (Html.BeginForm("Index", "Yorumlar", FormMethod.Post))
                            {
                                <div class="input-group input-group-sm">
                                    <input type="text" class="form-control" name="n" placeholder="Yorum ara...">
                                    <div class="input-group-append">
                                        <button class="btn btn-success" type="submit">
                                            <i class="fa fa-search"></i>
                                            Ara
                                        </button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <br />
                    <div class="table-responsive">
                        @foreach (var x in Model)
                        {
                            <table class="table shoping-cart-table">
                                <tbody>
                                    <tr>
                                        <td class="desc">
                                            <p class="small">
                                                @Html.Raw(x.Icerik)
                                            </p>
                                            <div class="m-t-sm">

                                                <a href="/Sorular/YanitSil/@x.Id" data-id="@x.Id" class="text-muted demo4"><i class="fa fa-trash"></i> Yanıtı Kaldır</a>
                                            </div>
                                        </td>
                                        <td width="200">
                                            <h4>
                                                @(((DateTime)x.CreatedAt).ToString("dd-MMM-yyyy"))
                                            </h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <hr />
                        }
                    </div>
                </div>
                <div class="ibox-content">
                    @*                    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
                    *@
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/admin/js/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    $('.demo4').on('click', function (event) {
        event.preventDefault();
        var btn = $(this);
        const url = $(this).attr('href');
        swal({
            title: 'Yanıtı Silmek İstediğinizden Emin Misiniz ?',
            text: "Yanıtı silmeniz durumunda kullanıcılar bu yanıta bir daha asla ulaşamayacaktır.",
            icon: 'info',
            buttons: ["Vazgeç", "Onayla!"],
        }).then(function (value) {
            if (value) {
                var id = btn.data("id");
                $.ajax({
                    url: "/Sorular/YanitSil/" + id,
                    type: "post",
                    dataType: "json",
                    success: function (func) {
                        window.location.reload();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        window.location.reload();
                    }
                });
            }
        });
    });
</script>