Uygulama/Controllers/KonularController.cs
using EgitimPortali.DTO;
using EgitimPortali.Request.Konular;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;

namespace Uygulama.Controllers
{
    [Authorize(Roles = "Admin")]

    public class KonularController : Controller
    {
        public async Task<IActionResult> ButunKonular()
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/Konular");
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var values = JsonConvert.DeserializeObject<List<KonularDto>>(jsonString);
            if (values != null)
                return View(values);
            else
                return RedirectToAction("GirisYap", "Login");
        }
        [HttpGet]
        public async Task<IActionResult> YeniKonuEkle()
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage2 = await httpClient.GetAsync("https://localhost:7179/api/Dersler");
            var jsonString = await responseMessage2.Content.ReadAsStringAsync();
            var values2 = JsonConvert.DeserializeObject<List<DerslerDto>>(jsonString);
            List<SelectListItem> categoryvalue = (from x in values2
                                                  select new SelectListItem
                                                  {
                                                      Text = x.Name,
                                                      Value = x.Id.ToString()

                                                  }).ToList();
            ViewBag.cv = categoryvalue;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> YeniKonuEkle(KonularPostRequest p)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage2 = await httpClient.GetAsync("https://localhost:7179/api/Dersler");
            var jsonString = await responseMessage2.Content.ReadAsStringAsync();
            var values2 = JsonConvert.DeserializeObject<List<DerslerDto>>(jsonString);
            List<SelectListItem> categoryvalue = (from x in values2
                                                  select new SelectListItem
                                                  {
                                                      Text = x.Name,
                                                      Value = x.Id.ToString()

                                                  }).ToList();
            ViewBag.cv = categoryvalue;

            var jsonEmployee = JsonConvert.SerializeObject(p);
            StringContent content = new StringContent(jsonEmployee, Encoding.UTF8, "application/json");
            var responseMessage = await httpClient.PostAsync("https://localhost:7179/api/Konular", content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("ButunKonular");
            }
            return View(p);
        }
        [HttpGet]
        public async Task<IActionResult> KonuGuncelle(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage2 = await httpClient.GetAsync("https://localhost:7179/api/Dersler");
            var jsonString = await responseMessage2.Content.ReadAsStringAsync();
            var values2 = JsonConvert.DeserializeObject<List<DerslerDto>>(jsonString);
            List<SelectListItem> categoryvalue = (from x in values2
                                                  select new SelectListItem
                                                  {
                                                      Text = x.Name,
                                                      Value = x.Id.ToString()

                                                  }).ToList();
            ViewBag.cv = categoryvalue;
            var responseMessage = await httpClient.GetAsync("https://localhost:7179/api/Konular/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonEmployee = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<KonularUpdateRequest>(jsonEmployee);
                if (values != null)
                    return View(values);
                else
                    return RedirectToAction("GirisYap", "Login");
            }
            return RedirectToAction("ButunKonular");
        }
        [HttpPost]
        public async Task<IActionResult> KonuGuncelle(KonularUpdateRequest p)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var jsonEmployee = JsonConvert.SerializeObject(p);
            var content = new StringContent(jsonEmployee, Encoding.UTF8, "application/json");
            var responseMessage = await httpClient.PutAsync("https://localhost:7179/api/Konular/" + p.Id, content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("ButunKonular");
            }
            return View(p);
        }
        public async Task<IActionResult> KonuSil(int id)
        {
            var httpClient = new HttpClient();
            var Token = Request.Cookies["tokenim"];
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue($"Bearer", $"{Token}");

            var responseMessage = await httpClient.DeleteAsync("https://localhost:7179/api/Konular/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("ButunKonular");
            }
            return View();
        }
    }
}

Uygulama/Views/Konular/ButunKonular.cshtml
@using EgitimPortali.DTO
@model List<KonularDto>
@{
    ViewData["Title"] = "ButunKonular";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/admin/css/plugins/dataTables/datatables.min.css" rel="stylesheet">
</head>
<body>
    <div id="wrapper">
        <a href="/Konular/YeniKonuEkle/" class="btn btn-info">Yeni Konu Ekle</a>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox ">
                        <div class="ibox-title">
                            <h5>Konular Listesi</h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Ders Adı</th>
                                            <th>Konu Adı</th>
                                            <th>Konuyu Düzenle</th>
                                            <th>Konuyu Sil</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var x in Model)
                                        {
                                            <tr class="gradeA">
                                                <td>@x.KonuSirasi</td>
                                                <td>@x.Dersler.Name</td>
                                                <td>@x.Name</td>
                                                <td><a href="/Konular/KonuGuncelle/@x.Id" class="btn btn-outline-success">Düzenle</a></td>
                                                <td><a href="/Konular/KonuSil/@x.Id" data-id="@x.Id" class="btn btn-outline-danger demo4">Sil</a></td>
                                            </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>#</th>
                                            <th>Ders Adı</th>
                                            <th>Konu Adı</th>
                                            <th>Konuyu Düzenle</th>
                                            <th>Konuyu Sil</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/admin/js/jquery-3.1.1.min.js" type="text/javascript"></script>
    <script src="~/admin/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/admin/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/admin/js/plugins/dataTables/datatables.min.js" type="text/javascript"></script>
    <script src="~/admin/js/plugins/dataTables/dataTables.bootstrap4.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        $('.demo4').on('click', function (event) {
            event.preventDefault();
            var btn = $(this);
            const url = $(this).attr('href');
            swal({
                title: 'Konuyu Silmek İstediğinizden Emin Misiniz ?',
                text: "Konuyu silmeniz durumunda kullanıcının bu konunun içerisindeki testlere ve içeriklere ulaşamayacaktır.",
                icon: 'info',
                buttons: ["Vazgeç", "Onayla!"],
            }).then(function (value) {
                if (value) {
                    var id = btn.data("id");
                    $.ajax({
                        url: "/Konular/KonuSil/" + id,
                        type: "post",
                        dataType: "json",
                        success: function (func) {
                            window.location.reload();
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            window.location.reload();
                        }
                    });
                }
            });
        });
    </script>
    <!-- Page-Level Scripts -->
    <script>
        $(document).ready(function () {
            $.noConflict();
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'ExampleFile' },
                    { extend: 'pdf', title: 'ExampleFile' },
                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]
            });
        });
    </script>
</body>
</html>

Uygulama/Views/Konular/KonuGuncelle.cshtml
@using EgitimPortali.Request.Konular
@model KonularUpdateRequest
@{
    ViewData["Title"] = "KonuGuncelle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Konu Güncelleme Sayfası</h1>

@using (Html.BeginForm("KonuGuncelle", "Konular", FormMethod.Post))
{
    <select asp-for="DerslerID" class="form-control" asp-items="@(List<SelectListItem>)ViewBag.cv">
         <option>Lütfen Konu Seçiniz</option>
    </select>
 
    <br />  
    @Html.HiddenFor(x=>x.Id)

    @Html.Label("Konu Adı")
    @Html.TextBoxFor(x=>x.Name, new { @class = "form-control" })
    <br />
    @Html.Label("Konu Sırası")
    @Html.TextBoxFor(x=>x.KonuSirasi, new { @class = "form-control" })
    <br />
    @Html.Label("Konu Görseli")
    @Html.TextBoxFor(x=>x.Resim, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Güncelle</button>
}

Uygulama/Views/Konular/YeniKonuEkle.cshtml
@using EgitimPortali.Request.Konular
@model KonularPostRequest
@{
    ViewData["Title"] = "YeniKonuEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Yeni Konu Ekleme Sayfası</h1>
@using (Html.BeginForm("YeniKonuEkle", "Konular", FormMethod.Post))
{
    <select asp-for="DerslerID" class="form-control" asp-items="@(List<SelectListItem>)ViewBag.cv">
         <option>Lütfen Ders Seçiniz</option>
    </select>
 
    <br />
    @Html.Label("Konu Adı")
    @Html.TextBoxFor(x=>x.Name, new { @class = "form-control" })
    @Html.Label("Konu Görseli")
    @Html.TextBoxFor(x=>x.Resim, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Ekle</button>
}